# Generated by Django 4.1.7 on 2023-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('stock_quantity', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
