# Generated by Django 4.1.7 on 2023-03-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_sale_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='buy_price',
            new_name='sell_price',
        ),
    ]
